version: '3'
services:
  aem-base:
    build:
      context: ./aem_base

  aem-author:
    build:
      context: ./author/
      dockerfile: Dockerfile
    depends_on:
      - aem-base
    ports:
      - "4502:4502"
    volumes:
      - aem_author:/opt/aem/crx-quickstart
  aem-publisher:
    build:
      context: ./publisher/
      dockerfile: Dockerfile
    depends_on:
      - aem_base
    ports:
      - "4503/4503"
    volumes:
      - aem_publisher:/opt/aem/crx-quickstart
volumes:
  aem_author:
    driver: local
    driver_opts:
      type: none
      device: ./data/aem_author_data
      o: bind
  aem_publisher:
    driver: local
    driver_opts:
      type: none
      device: ./data/aem_author_data
      o: bind
