services:
  aem-base:
    build: ./aem_base

  aem-author:
    build: ./author
    depends_on:
      - aem-base
    ports:
      - "4502:4502"

  # aem-publish:
  #   build: publish
  #   ports:
  #     - "4503:4503"

  # aem-dispatcher:
  #   build: dispatcher
  #   ports:
  #     - "80:80"
  #   links:
  #     - aem-author
  #     - aem-publish

# volumes:
#   aem-author:
#     driver: local